const ADD_TASK = 'ADD_TASK';
const TOGGLE_TASK_DONE = 'TOGGLE_TASK_DONE';
const TOGGLE_TASK_IMPORTANT = 'TOGGLE_TASK_IMPORTANT';
const REMOVE_TASK = 'REMOVE_TASK';

export {
  ADD_TASK,
  TOGGLE_TASK_DONE,
  TOGGLE_TASK_IMPORTANT,
  REMOVE_TASK
}