const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
const ADD_TASK = 'ADD_TASK';

const DELETE_REQUEST_TASK = 'DELETE_REQUEST_TASK';
const DELETE_TASK = 'DELETE_TASK'

const TOGGLE_TASK_DONE = 'TOGGLE_TASK_DONE';

const TASK_IMPORTANT_REQUEST = 'TASK_IMPORTANT_REQUEST';
const TASK_IMPORTANT = 'TASK_IMPORTANT';


const TASKS_REQUEST = 'TASKS_REQUEST';
const TASKS = 'TASKS';

export {
  ADD_TASK_REQUEST,
  ADD_TASK,

  TOGGLE_TASK_DONE,

  TASK_IMPORTANT_REQUEST,
  TASK_IMPORTANT,

  DELETE_TASK,
  DELETE_REQUEST_TASK,

  TASKS_REQUEST,
  TASKS
}