const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
const ADD_TASK = 'ADD_TASK';

const TOGGLE_TASK_DONE = 'TOGGLE_TASK_DONE';
const TOGGLE_TASK_IMPORTANT = 'TOGGLE_TASK_IMPORTANT';
const REMOVE_TASK = 'REMOVE_TASK';

const TASKS_REQUEST = 'TASKS_REQUEST';
const TASKS = 'TASKS';

export {
  ADD_TASK_REQUEST,
  ADD_TASK,

  TOGGLE_TASK_DONE,
  TOGGLE_TASK_IMPORTANT,
  REMOVE_TASK,

  TASKS_REQUEST,
  TASKS
}