const ADD_TODO = 'ADD_TODO';
const TOGGLE_TODO_DONE = 'TOGGLE_TODO_DONE';
const TOGGLE_TODO_IMPORTANT = 'TOGGLE_TODO_IMPORTANT';
const REMOVE_TODO = 'REMOVE_TODO';

export {
  ADD_TODO,
  TOGGLE_TODO_DONE,
  TOGGLE_TODO_IMPORTANT,
  REMOVE_TODO
}